### PR TITLE
Duration formatting on axes

### PR DESCRIPTION
**Pull request by easternbloc**
https://www.agileplannerapp.com/boards/15088/cards/9375

This was previously not possible for grouped timeseries graphs.

I've tried to make the graph formatting a bit more sane by removing the old key of currency and tried to refactor everything to just use formatOptions.

We also had issues in stagecraft where format-options and format keys were both doing the same thing so I've refactored it to just use format.

This means we'll need to update stagecraft. And bug bash.

### CODE REVIEW

**Comment by jabley** [comment]
I would like us to use `{}` in preference to scalar values (in terms of exposing a data format from stagecraft that clients other than ones we control can consume):

1. They allow evolution over time without breaking clients that we might not control.
1. Statically types languages such as `Go` prefer / mandate a static type for a field, rather than a union type of scalar or complex type.

**Comment by jonnywyatt** [comment]
@jabley - can you explain what you mean by a scalar value in this context? ta

**Comment by jabley** [comment]
Sorry, slight Perl-ism.
```json
"format" : "number"
```
compared with 
```json
"format": { "type": "number" }
```

The latter can support evolving over time without needing to upgrade all clients at the same time.

For the former, you'd need to add a new field (say, `formatOptions`) and gradually upgrade all clients until you deprecate the `format` field.

It can be hard to decide when to use each type.

**Comment by easternbloc** [comment]
@jabley @jonnywyatt  I updated to docs to avoid this now. Let it be known that all formatting will use objects!!!

**Comment by jonnywyatt** [comment]
@jabley - makes good sense thanks!

**Pull request merged**
